################   【api-code公共配置】 ################
shsnc:
  project:
    swaggerEnable: true
    namespace: ${spring.application.name}
    #文档访问秘钥
    access-key: fa404159-c134-43af-860f-b86a87d4681d
server:
  port: 19520
  servlet:
    context-path: /${spring.application.name}
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: aly-monitor
  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      #最大连接池数量
      maxActive: 20
      #初始化时建立物理连接的个数
      initialSize: 1
      #获取连接时最大等待时间，单位毫秒
      maxWait: 60000
      #最小连接池数量
      minIdle: 1
      #Destroy线程会检测连接的间隔时间
      timeBetweenEvictionRunsMillis: 60000
      #最小空闲时间，默认30分钟，如果一条连接30分钟都没有使用到，并且这种连接的数量超过了minIdle，则这些连接就会被关闭了
      minEvictableIdleTimeMillis: 300000
      #用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用
      validationQuery: select 'x'
      #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      testWhileIdle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnBorrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false
      #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭
      poolPreparedStatements: false
      #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      maxOpenPreparedStatements: 20
  ################         【 kafka默认配置】   ################
  kafka:
    consumer:
      #默认消费组
      group-id: ${spring.application.name}
      #是否开启自动提交，true开启，false关闭
      enable-auto-commit: false
      #从提交的offset开始消费
      auto-offset-reset: latest
      #消费者消息序列化器
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 10
    producer:
      #生产者消息序列化器
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
  security:
    user:
      name: shsnc
      password: shsnc!@#
  main:
    allow-bean-definition-overriding: true

################         【 mybatis默认配置】   ################
mybatis:
  #xml文件的扫描路径
  mapperLocations: classpath:mappers/**/*Mapper.xml
  configuration:
    #指定MyBatis中的日志文件名称的前缀
    log-prefix: SQL.
    #设置数据库的超时响应时间
    default-statement-timeout: 60

################         【springboot默认配置】   ################
feign:
  client:
    config:
      default:
        #设置请求链接的超时时间
        connectTimeout: 60000
        #设置请求处理的超时时间
        readTimeout: 60000
  hystrix:
    #feign是否开启hystrix熔断，true开启，false关闭
    enabled: false

################         【配置文件加密配置】      ################
jasypt:
  encryptor:
    #配置文件加密秘钥
    password: edbc98f4-c52f-4adb-8ffe-31b51ce33bb7

################         【springboot监控配置】   ################
management:
  info:
    git:
      #获取更全面的git信息
      mode: full
  endpoint:
    health:
      #查看应用健康详细的信息
      show-details: always
  endpoints:
    web:
      exposure:
      #启用springboot所有的监控端点
        include: '*'
  health:
    elasticsearch:
      #是否开启elasticsearch健康检查，true开启，false关闭
      enabled: false